var goog;
goog.global;
goog.isArrayLike;
var process;
process.hrtime;
RegExp.prototype.schema$core$Schema$;
RegExp.prototype.schema$core$Schema$spec$arity$1;
RegExp.prototype.schema$core$Schema$explain$arity$1;
Int8Array.prototype.set;
Int8Array.prototype.fill;
Int8Array.prototype.length;
Uint8Array.prototype.length;
var module;
module.exports;
Object.exec;
Object.index;
Object.install;
var require;
