var goog;
goog.global;
goog.isArrayLike;
var process;
process.hrtime;
RegExp.prototype.schema$core$Schema$;
RegExp.prototype.schema$core$Schema$spec$arity$1;
RegExp.prototype.schema$core$Schema$explain$arity$1;
var setTimeout;
var Java;
Java.type;
Object.out;
Object.out.println;
Object.error;
Object.error.println;
Object.exec;
Object.index;
Object.install;
Int8Array.prototype.set;
Int8Array.prototype.fill;
Int8Array.prototype.length;
Int8Array.prototype.slice;
Uint8Array.prototype.length;
var require;
var pako;
pako.deflate;
pako.inflate;
